version: '3.5'
services:
  fullstack:
    image: fullstack
    build: 
      context: .
      dockerfile: ./docker-files/fullstack.Dockerfile
      target: fullstack
      args:
        WORKINGUSER: cmolli
    container_name: fullstack
    privileged: true
    volumes:
      - type: bind
        source: /home/tanya/piknship/docker/users/cmolli/fs/.vscode
        target: /home/cmolli/.vscode
      - type: bind
        source: /home/tanya/piknship/docker/users/cmolli/fs/.android
        target: /home/cmolli/.android
      - type: bind
        source: /home/tanya/piknship/docker/users/cmolli/fs/.pub-cache
        target: /usr/lib/thirdparty/flutter/.pub-cache
      - type: bind
        source: /home/tanya/piknship/docker/users/cmolli/fs/.config
        target: /home/cmolli/.config
      - type: bind
        source: /home/tanya/piknship/docker/users/cmolli/fs/android-sdk-linux
        target: /usr/lib/thirdparty/android-sdk-linux
      - type: bind
        source: /home/tanya/piknship/docker/users/cmolli/db
        target: /data/db
      - type: bind
        source: /home/tanya/piknship/code
        target: /opt/piknship/code
      - type: bind
        source: /home/tanya/piknship/config
        target: /opt/piknship/config
      - type: bind
        source: /home/tanya/piknship/misc
        target: /opt/piknship/misc
      - type: bind
        source: /home/tanya/piknship/docker/users/cmolli/logs
        target: /opt/piknship/logs
      - type: bind
        source: /home/tanya/piknship/misc/keys/app-keys
        target: /opt/piknship/keys

    environment: 
      - ROOT_PASSWORD=piknshiprockz
      - WORKINGUSER=cmolli
      - WORKINGUSER_PASSWORD=piknshiprockz
      - MONGO_INITDB_DATABASE=piknship
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=piknshiprockz
    ports:
      - "3389:3389"
      - "1337:1337"
      - "8000:8000"
      - "80:80"
      - "4200:4200"
      - "27017:27017"
      - "5055:5055"
    tty: true
    networks:
      piknship:
        ipv4_address: 172.20.0.2

networks:
  piknship:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
        # - gateway: 172.20.0.1